# 土曜日に動くやつ
version: 0.2

env: 
  variables:
    recreate_action: date
    job_description: this is local test01
    ACCOUNT_ID: "sandbox_dayo!"
    ES_SERVER: "http://demodayo.ap-northeast-1.elasticbeanstalk.com"
  exported-variables:
    - ACCOUNT_ID
    - ES_SERVER

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # - yum update -y
      - yum install jq python-pip -y
      - pip install --upgrade awscli
  build:
    commands:
      #  - . ${CODEBUILD_SRC_DIR}/script/demo_sand_aurora.env
       - cd ${CODEBUILD_SRC_DIR}/script/
       - aws --version
       - echo "${job_description}"
       - |
            if [ $recreate_action = "date" ]; then
              aws codebuild list-projects
              aws codebuild start-build --project-name test-poc
            elif [ $recreate_action = "pwd" ];then
              sh ${CODEBUILD_SRC_DIR}/script/pwd.sh
            elif [ $recreate_action = "id" ];then
              id
            else
              echo "command specify error"
            fi
  # post_build:
  #   commands:
  #     - echo "Complate run ${recreate_action}!"
  #     - |
  #          if [ $recreate_action = "date" ]; then
  #            aws codebuild start-build --project-name test-poc
  #          else
  #            echo "finish"
  #          fi
