version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  build:
    commands:
      - aws --version
  post_build:
    commands:
      - echo "finish!!"
