# 土曜日に動くやつ
version: 0.2

phases:
  build:
    runtime-versions:
      python: 3.7    
    commands:
       - cd ${CODEBUILD_SRC_DIR}/script/
       - pwd
       - echo "${job_description}"
       - |
            if [ $recreate_action = "date" ]; then
                date
            elif [ $recreate_action = "pwd" ];then
                pwd
            elif [ $recreate_action = "id" ];then
                id
            else
                echo "command specify error"
                exit 1
            fi