# 土曜日に動くやつ
version: 0.2

env: 
  variables:
    recreate_action: date
    job_description: this is local test01

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apk --update add jq
      - pip install --upgrade awscli
  build:
    commands:
       - cd ${CODEBUILD_SRC_DIR}/script/
       - pwd
       - aws --version
       - echo "${job_description}"
       - |
            if [ $recreate_action = "date" ]; then
              date
            elif [ $recreate_action = "pwd" ];then
              pwd
            elif [ $recreate_action = "id" ];then
              id
            else
              echo "command specify error"
            fi